import asyncio
import hashlib
import json
import os
from http import HTTPStatus
from pathlib import Path
from typing import Optional, Set

import typer
from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
import uvicorn

from franken_stream.async_scraper import AsyncContentScraper
from franken_stream.cache import FTSCache
from franken_stream.player import PremiumPlayer
from franken_stream.preloader import PredictiveLoader
from franken_stream.providers import ProviderManager
from franken_stream.real_debrid import get_client as get_rd_client
from franken_stream.scraper import ContentScraper
from franken_stream.watchlist import Watchlist

app = typer.Typer(help="Web UI server commands")

# Create FastAPI app
web_app = FastAPI(title="Franken-Stream Web UI", version="0.1.0")

# Module-level singletons — shared across all requests
_player = PremiumPlayer()
_watchlist = Watchlist()
_ws_clients: Set[WebSocket] = set()

# Shared scraper + preloader kept alive for the duration of the server process
_shared_pm = ProviderManager()
_shared_scraper: Optional[AsyncContentScraper] = None
_preloader: Optional[PredictiveLoader] = None


def _get_preloader() -> PredictiveLoader:
    global _shared_scraper, _preloader
    if _shared_scraper is None:
        _shared_scraper = AsyncContentScraper(provider_manager=_shared_pm)
        _preloader = PredictiveLoader(_shared_scraper)
    return _preloader

WEB_UI_DIR = Path(__file__).resolve().parent / "web_ui"
INDEX_FILE = WEB_UI_DIR / "index.html"


# Mount static assets generated by Vite build
_ASSETS_DIR = WEB_UI_DIR / "assets"
if _ASSETS_DIR.exists():
    web_app.mount("/assets", StaticFiles(directory=str(_ASSETS_DIR)), name="assets")


CINEMA_FILE = WEB_UI_DIR / "cinema.html"


@web_app.get("/", response_class=HTMLResponse)
async def root():
    """Serve the main web UI"""
    if not INDEX_FILE.exists():
        raise HTTPException(status_code=404, detail="Web UI not found")
    return FileResponse(INDEX_FILE, media_type="text/html")


@web_app.get("/cinema", response_class=HTMLResponse)
async def cinema():
    """Serve the TV Cinema Mode UI"""
    if not CINEMA_FILE.exists():
        raise HTTPException(status_code=404, detail="Cinema UI not found")
    return FileResponse(CINEMA_FILE, media_type="text/html")


@web_app.get("/api/health")
async def get_health():
    """Get provider health status"""
    try:
        pm = ProviderManager()
        health_data = pm.get_health_summary()
        return {"status": "ok", "providers": health_data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@web_app.get("/api/providers")
async def get_providers():
    """Get available search providers"""
    try:
        pm = ProviderManager()
        search_bases = pm.get_ranked_search_bases()
        return {"status": "ok", "search_bases": search_bases}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _enrich(item: dict) -> dict:
    """Pass-through enrichment hook for search results."""
    return item


@web_app.post("/api/v1/search")
async def v1_search(request: Request):
    data = await request.json()
    query = data.get("query", "").strip()
    if not query:
        raise HTTPException(status_code=400, detail="query is required")

    # FTS5 cache check
    fts = FTSCache()
    cached = fts.lookup(query)
    if cached:
        results = [_enrich({"title": t, "url": u}) for t, u in cached]
        asyncio.create_task(_get_preloader().preload(cached[:3]))
        return {"status": "ok", "query": query, "results": results, "cached": True}

    pm = ProviderManager()
    scraper = AsyncContentScraper(provider_manager=pm)
    try:
        bases = pm.get_ranked_search_bases()
        scraper_results, plugin_results = await asyncio.gather(
            scraper.search(query, bases),
            pm.search_plugins(query),
            return_exceptions=True,
        )
        if isinstance(scraper_results, Exception):
            scraper_results = []
        if isinstance(plugin_results, Exception):
            plugin_results = []

        # Merge all results, score by relevance, deduplicate by URL
        from franken_stream.async_scraper import _relevance_score
        seen: set = set()
        scored = []
        for title, url in scraper_results:
            if url not in seen:
                seen.add(url)
                scored.append((_relevance_score(title, query), title, url))
        for item in plugin_results:
            # plugin_results are MediaItem objects
            title = getattr(item, "title", "") if not isinstance(item, tuple) else item[0]
            url = getattr(item, "url", "") if not isinstance(item, tuple) else item[1]
            if url and url not in seen:
                seen.add(url)
                scored.append((_relevance_score(title, query), title, url))

        # Best matches first
        scored.sort(key=lambda x: (-x[0], x[1]))
        raw = [(t, u) for _, t, u in scored]

        if raw:
            fts.store(query, raw)
        asyncio.create_task(_get_preloader().preload(raw[:3]))
        results = [_enrich({"title": t, "url": u}) for t, u in raw]
        return {"status": "ok", "query": query, "results": results, "cached": False}
    finally:
        await scraper.close()


@web_app.post("/api/search")
async def search(request: Request):
    """Search for movies/shows"""
    try:
        data = await request.json()
        query = data.get("query", "").strip()

        if not query:
            raise HTTPException(status_code=400, detail="Query is required")

        # FTS5 cache check
        fts = FTSCache()
        cached = fts.lookup(query)
        if cached:
            return {
                "status": "ok",
                "query": query,
                "results": [{"title": t, "url": u} for t, u in cached],
                "cached": True,
            }

        pm = ProviderManager()
        scraper = AsyncContentScraper(provider_manager=pm)
        try:
            bases = pm.get_ranked_search_bases()
            raw = await scraper.search(query, bases)
            if raw:
                fts.store(query, raw)
            return {
                "status": "ok",
                "query": query,
                "results": [{"title": title, "url": url} for title, url in raw],
                "cached": False,
            }
        finally:
            await scraper.close()
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@web_app.post("/api/embed")
async def get_embed(request: Request):
    """Extract embed URL from a page"""
    try:
        data = await request.json()
        page_url = data.get("url")
        base_url = data.get("base_url")

        if not page_url:
            raise HTTPException(status_code=400, detail="URL is required")

        pm = ProviderManager()
        scraper = ContentScraper(provider_manager=pm)

        embed_url = scraper.fetch_embed_from_page(page_url, base_url=base_url)

        return {"status": "ok", "embed_url": embed_url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── v1 Provider / Skills ──────────────────────────────────────────────────────

@web_app.get("/api/v1/providers")
async def v1_providers():
    pm = ProviderManager()
    return {
        "status": "ok",
        "search_bases": pm.get_ranked_search_bases(),
        "embed_fallbacks": pm.get_embed_fallbacks(),
        "health": pm.get_health_summary(),
    }


@web_app.get("/api/v1/skills/manifest")
async def v1_skills_manifest():
    return {
        "skill": {
            "id": "franken-stream",
            "name": "Franken-Stream Media Player",
            "version": "2.0.0",
            "description": "Search and play movies/TV shows from multiple providers",
        },
        "endpoints": {
            "base_url": "http://localhost:8000/api/v1",
            "websocket": "ws://localhost:8000/api/ws",
        },
        "actions": {
            "search_media": "POST /api/v1/search",
            "play_media":   "POST /api/v1/player/spin-up",
            "control":      "POST /api/v1/player/control",
            "status":       "GET  /api/v1/player/status",
            "providers":    "GET  /api/v1/providers",
        },
    }


@web_app.get("/api/v1/embed/{media_id}")
async def v1_embed(media_id: str):
    pm = ProviderManager()
    scraper = AsyncContentScraper(provider_manager=pm)
    try:
        embed_url = await scraper.fetch_embed_from_page(media_id)
        return {"status": "ok", "embed_url": embed_url}
    finally:
        await scraper.close()


# ── v1 Playback (direct URL) ──────────────────────────────────────────────────

@web_app.get("/api/v1/real-debrid/status")
async def rd_status():
    """Return Real-Debrid availability and account info."""
    rd = get_rd_client()
    if rd is None:
        return {"available": False, "reason": "REAL_DEBRID_API_KEY not set"}
    alive = await rd.is_alive()
    if not alive:
        return {"available": False, "reason": "Invalid or expired API key"}
    return {"available": True}


@web_app.post("/api/v1/unrestrict")
async def rd_unrestrict(request: Request):
    """Unrestrict a URL via Real-Debrid. Returns {url} on success."""
    data = await request.json()
    source_url = data.get("url", "").strip()
    if not source_url:
        raise HTTPException(status_code=400, detail="url is required")

    rd = get_rd_client()
    if rd is None:
        return {"url": None, "reason": "Real-Debrid not configured"}

    premium_url = await rd.unrestrict(source_url)
    if premium_url:
        return {"url": premium_url, "original": source_url}
    return {"url": None, "reason": "URL not supported or unrestriction failed"}


@web_app.post("/api/v1/extract")
async def v1_extract(request: Request):
    """Extract the embeddable player URL from a content page (async)."""
    data = await request.json()
    page_url = data.get("url", "").strip()
    if not page_url:
        raise HTTPException(status_code=400, detail="url is required")

    pm = ProviderManager()
    scraper = AsyncContentScraper(provider_manager=pm)
    try:
        embed_url = await scraper.fetch_embed_from_page(page_url)
        return {"status": "ok", "embed_url": embed_url, "fallback": page_url}
    except Exception:
        return {"status": "ok", "embed_url": None, "fallback": page_url}
    finally:
        await scraper.close()


@web_app.get("/api/v1/poster")
async def v1_poster(title: str, year: Optional[str] = None):
    """
    Return a poster image URL for a movie/show title.
    Requires TMDB_API_KEY env var. Returns null poster_url if unavailable.
    """
    import aiohttp as _aio
    tmdb_key = os.environ.get("TMDB_API_KEY", "")
    if not tmdb_key:
        return {"poster_url": None, "source": "none"}

    try:
        params: dict = {"api_key": tmdb_key, "query": title, "page": 1}
        if year:
            params["year"] = year
        async with _aio.ClientSession() as s:
            async with s.get(
                "https://api.themoviedb.org/3/search/multi",
                params=params,
                timeout=_aio.ClientTimeout(total=5),
            ) as r:
                if r.status == 200:
                    data = await r.json()
                    for item in data.get("results", [])[:4]:
                        poster = item.get("poster_path")
                        if poster:
                            return {
                                "poster_url": f"https://image.tmdb.org/t/p/w342{poster}",
                                "source": "tmdb",
                            }
    except Exception:
        pass

    return {"poster_url": None, "source": "none"}


@web_app.post("/api/v1/play")
async def v1_play(request: Request):
    data = await request.json()
    url = data.get("url", "").strip()
    title = data.get("title", "")
    if not url:
        raise HTTPException(status_code=400, detail="url is required")

    # Attempt Real-Debrid unrestriction if configured
    rd = get_rd_client()
    if rd is not None:
        try:
            premium = await rd.unrestrict(url)
            if premium:
                url = premium
        except Exception:
            pass

    result = await _player.play(url, title=title)
    if result.get("status") == "playing":
        media_id = hashlib.md5(url.encode()).hexdigest()[:12]
        _watchlist.add(media_id, title or url, url)
    await _broadcast({"type": "playback", "event": "started", **result})
    return result


@web_app.post("/api/v1/control")
async def v1_control(request: Request):
    data = await request.json()
    action = data.get("action", "")
    ok = False

    if action == "pause":
        ok = await _player.pause()
    elif action == "resume":
        ok = await _player.resume()
    elif action == "stop":
        await _player.stop()
        ok = True
    elif action == "seek":
        position = data.get("position")
        if position is None:
            raise HTTPException(status_code=400, detail="position required for seek")
        ok = await _player.seek(int(position))
    else:
        raise HTTPException(status_code=400, detail=f"Unknown action: {action}")

    await _broadcast({"type": "playback", "event": action, "ok": ok})
    return {"action": action, "ok": ok}


@web_app.get("/api/v1/status")
async def v1_status():
    return await _player.get_status()


# ── v1 Player (agent one-shot spin-up) ───────────────────────────────────────

@web_app.post("/api/v1/player/spin-up")
async def player_spin_up(request: Request):
    """
    Agent one-shot: search → extract embed → play.
    POST {"query": "Oppenheimer", "quality": "best"}
    """
    data = await request.json()
    query = data.get("query", "").strip()
    if not query:
        raise HTTPException(status_code=400, detail="query is required")

    # 1. Search
    fts = FTSCache()
    cached = fts.lookup(query)
    if cached:
        raw = cached
    else:
        pm = ProviderManager()
        scraper = AsyncContentScraper(provider_manager=pm)
        try:
            bases = pm.get_ranked_search_bases()
            raw = await scraper.search(query, bases)
            if raw:
                fts.store(query, raw)
        finally:
            await scraper.close()

    if not raw:
        raise HTTPException(status_code=404, detail=f"No results found for: {query}")

    title, page_url = raw[0]

    # 2. Extract embed
    pm2 = ProviderManager()
    scraper2 = AsyncContentScraper(provider_manager=pm2)
    try:
        embed_url = await scraper2.fetch_embed_from_page(page_url)
        play_url = embed_url or page_url
    finally:
        await scraper2.close()

    # 3. Optionally unrestrict via Real-Debrid
    rd = get_rd_client()
    if rd is not None:
        try:
            premium = await rd.unrestrict(play_url)
            if premium:
                play_url = premium
        except Exception:
            pass

    # 4. Spin up player
    result = await _player.play(play_url, title=title)
    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail=result.get("message", "Player error"))

    media_id = hashlib.md5(play_url.encode()).hexdigest()[:12]
    _watchlist.add(media_id, title, play_url)
    await _broadcast({"type": "playback", "event": "spin-up", "title": title})
    return {
        "status": "playing",
        "media": {"title": title, "url": play_url},
        "message": f"Now playing: {title}",
        **result,
    }


@web_app.get("/api/v1/player/status")
async def player_status():
    return await _player.get_status()


@web_app.post("/api/v1/player/control")
async def player_control(request: Request):
    return await v1_control(request)


# ── Watchlist ─────────────────────────────────────────────────────────────────

@web_app.get("/api/v1/watchlist")
async def watchlist_list():
    return {"status": "ok", "items": _watchlist.all()}


@web_app.get("/api/v1/watchlist/in-progress")
async def watchlist_in_progress():
    return {"status": "ok", "items": _watchlist.in_progress()}


@web_app.post("/api/v1/watchlist")
async def watchlist_add(request: Request):
    data = await request.json()
    title = data.get("title", "").strip()
    url = data.get("url", "").strip()
    if not title or not url:
        raise HTTPException(status_code=400, detail="title and url are required")
    media_id = data.get("id") or hashlib.md5(url.encode()).hexdigest()[:12]
    _watchlist.add(
        media_id,
        title,
        url,
        provider=data.get("provider", ""),
        year=data.get("year"),
        media_type=data.get("media_type", "movie"),
        quality=data.get("quality", "unknown"),
    )
    return {"status": "ok", "id": media_id}


@web_app.patch("/api/v1/watchlist/{media_id}")
async def watchlist_update(media_id: str, request: Request):
    data = await request.json()
    progress = data.get("progress_seconds")
    if progress is None:
        raise HTTPException(status_code=400, detail="progress_seconds is required")
    _watchlist.update_progress(media_id, int(progress), data.get("duration_seconds"))
    return {"status": "ok"}


@web_app.delete("/api/v1/watchlist/{media_id}")
async def watchlist_remove(media_id: str):
    _watchlist.remove(media_id)
    return {"status": "ok"}


# ── WebSocket ─────────────────────────────────────────────────────────────────

async def _broadcast(msg: dict) -> None:
    """Push a JSON message to all connected WebSocket clients."""
    dead: Set[WebSocket] = set()
    for ws in list(_ws_clients):
        try:
            await ws.send_json(msg)
        except Exception:
            dead.add(ws)
    _ws_clients.difference_update(dead)


@web_app.websocket("/api/ws")
async def websocket_endpoint(ws: WebSocket):
    await ws.accept()
    _ws_clients.add(ws)
    await ws.send_json({"type": "connected", "message": "Franken-Stream WebSocket ready"})
    try:
        while True:
            data = await ws.receive_json()
            if data.get("action") == "ping":
                await ws.send_json({"type": "pong"})
            elif data.get("action") == "status":
                status = await _player.get_status()
                await ws.send_json({"type": "status", **status})
    except WebSocketDisconnect:
        pass
    finally:
        _ws_clients.discard(ws)


# ── CLI entry point ───────────────────────────────────────────────────────────

@app.callback(invoke_without_command=True)
def serve(
    host: str = typer.Option("127.0.0.1", "--host", "-h", help="Host to bind the web server."),
    port: int = typer.Option(8000, "--port", "-p", help="Port for the web server."),
) -> None:
    """Start the Franken-Stream Web UI server."""
    typer.echo(f"Starting Franken-Stream Web UI at http://{host}:{port}")
    uvicorn.run(web_app, host=host, port=port)
