#!/bin/bash
# Quick guide to get Groq API key and setup .env

echo "======================================================================"
echo "                   CRYPTOCALL FM – GET GROQ API KEY"
echo "======================================================================"
echo ""
echo "Follow these steps to get a free Groq API key:"
echo ""
echo "1. Open browser: https://console.groq.com"
echo ""
echo "2. Sign up (no credit card required)"
echo ""
echo "3. Go to 'API Keys' section"
echo ""
echo "4. Click 'Create API Key'"
echo ""
echo "5. Copy the key that starts with 'gsk_'"
echo ""
echo "======================================================================"
echo ""
echo "6. Add to .env file:"
echo ""
echo "   GROQ_API_KEY=gsk_<your_key_here>"
echo "   LLM_ENDPOINT=groq"
echo "   LLM_MODEL=mixtral-8x7b-32768"
echo "   GROK_API_KEY=gsk_<same_key>"
echo ""
echo "======================================================================"
echo ""
echo "7. Test it works:"
echo ""
echo "   npm run test:pilots"
echo ""
echo "======================================================================"
echo ""
echo "Expected output:"
echo "   ✓ Groq API success"
echo "   ✓ Research agent generated 5 talking points"
echo "   ✓ Script agent generated episode script"
echo ""
echo "======================================================================"
echo ""
echo "DONE! Your CryptoCall FM is now using real LLM instead of mocks."
echo ""
